### ISSUE TITLE
Manage Python

### ISSUE THREAD

**Issue by MichaelCurrin** [MichaelCurrin/ansible-playbooks#1]
Things may break if this is updated.

Will virtual envs break? what about pyenv?

Is it possible to run Ansible across the network on a machine without ansible and python installed?

```
  - name: Install Python 
    apt: 
      name:      
        - python3
      state: present

```
